cd ..
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q1  --suffix=_adam_1 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q1  --suffix=_adam_2 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q1  --suffix=_adam_3 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q1  --suffix=_adam_4 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q1  --suffix=_adam_5 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=HT  --suffix=_adam_1 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=HT  --suffix=_adam_2 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=HT  --suffix=_adam_3 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=HT  --suffix=_adam_4 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=HT  --suffix=_adam_5 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q2  --suffix=_adam_1 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q2  --suffix=_adam_2 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q2  --suffix=_adam_3 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q2  --suffix=_adam_4 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q2  --suffix=_adam_5 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q4  --suffix=_adam_1 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q4  --suffix=_adam_2 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q4  --suffix=_adam_3 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q4  --suffix=_adam_4 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q4  --suffix=_adam_5 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q6  --suffix=_adam_1 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q6  --suffix=_adam_2 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q6  --suffix=_adam_3 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q6  --suffix=_adam_4 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q6  --suffix=_adam_5 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q8  --suffix=_adam_1 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q8  --suffix=_adam_2 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q8  --suffix=_adam_3 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q8  --suffix=_adam_4 --arch=resnet
CUDA_VISIBLE_DEVICES=1 python train.py --dataset=cifar100 --load_model=Q8  --suffix=_adam_5 --arch=resnet