cd ..
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_1 --arch=resnet34
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_2 --arch=resnet34
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_3 --arch=resnet34
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_4 --arch=resnet34
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_5 --arch=resnet34
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_1 --arch=resnet50
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_2 --arch=resnet50
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_3 --arch=resnet50
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_4 --arch=resnet50
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_5 --arch=resnet50
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_1 --arch=resnet101
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_2 --arch=resnet101
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_3 --arch=resnet101
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_4 --arch=resnet101
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_5 --arch=resnet101
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_1 --arch=vgg19
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_2 --arch=vgg19
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_3 --arch=vgg19
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_4 --arch=vgg19
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_5 --arch=vgg19
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_1 --arch=vgg19bn
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_2 --arch=vgg19bn
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_3 --arch=vgg19bn
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_4 --arch=vgg19bn
CUDA_VISIBLE_DEVICES=0 python train.py --dataset=cifar100 --suffix=_5 --arch=vgg19bn
