cd .. 
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11bn
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11bn
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11bn
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11bn
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11bn
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg11
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128
# CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet101
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet101
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet101
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet101
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet101
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet34
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet34
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet34
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet34
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet34
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19bn
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19bn
CUDA_VISIBLE_DEVICES=0 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19bn
CUDA_VISIBLE_DEVICES=0 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19bn
CUDA_VISIBLE_DEVICES=0 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19bn
CUDA_VISIBLE_DEVICES=0 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=vgg19
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_1 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet50
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_2 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet50
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_3 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet50
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_4 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet50
CUDA_VISIBLE_DEVICES=0  python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=arch --suffix_load=_5 --attack=cw --conf=30  --iterations=100 --train_batch_size=128 --test_batch_size=128 --arch_load=resnet50
