cd ..

CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_1" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=1
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_1" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=2
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_1" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=4
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_1" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=8
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_1" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=16
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_2" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=1
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_2" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=2
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_2" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=4
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_2" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=8
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_2" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=16
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_3" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=1
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_3" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=2
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_3" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=4
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_3" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=8
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_3" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=16
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_4" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=1
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_4" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=2
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_4" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=4
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_4" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=8
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_4" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=16
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_5" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=1
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_5" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=2
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_5" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=4
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_5" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=8
CUDA_VISIBLE_DEVICES=1 python trans.py  --dataset=cifar100 --save_path=./outputs/ --use_lib=advertorch --analysis=act --arch=resnet --attack=cw --iteration=100 --conf=30 --suffix_load="_5" --load_model=FP --test_batch_size=128 --dorefa_load=True --dorefa_test=True --abit_load=16
