CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=FP --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=Q1 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=Q2 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=Q4 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=Q6 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=Q8 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_1" --dataset=cifar10 --load_model=HT --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=FP --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=Q1 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=Q2 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=Q4 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=Q6 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=Q8 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_2" --dataset=cifar10 --load_model=HT --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=FP --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=Q1 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=Q2 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=Q4 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=Q6 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=Q8 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_3" --dataset=cifar10 --load_model=HT --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=FP --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=Q1 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=Q2 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=Q4 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=Q6 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=Q8 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_4" --dataset=cifar10 --load_model=HT --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=FP --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=Q1 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=Q2 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=Q4 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=Q6 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=Q8 --test_batch_size=128
CUDA_VISIBLE_DEVICES=3 python trans.py --use_lib=advertorch --analysis=quant --arch=resnet --attack=PGD --suffix_load="_5" --dataset=cifar10 --load_model=HT --test_batch_size=128
